name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix['node-version'] }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run check-types

      - name: Lint
        run: npm run lint

      - name: Compile
        run: npm run compile

      - name: Test
        run: npm run test

      - name: Package
        run: npm run package

      - name: Create VSIX package
        run: npx @vscode/vsce package --no-dependencies

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: "*.vsix"
          if-no-files-found: error
